### ISSUE TITLE
 How to use rt-utils to convert nii files to dicom (rtstruct)?

### ISSUE THREAD

**Issue by 1413194910** [qurit/rt-utils#108]
I saw that some experts used rt-utils to convert nii to dicom (rtstruct), but I didn’t see any examples in the instructions, so I don’t know how to do it.

**Comment by JianJuly** [comment]
try this
'''
from rt_utils import RTStructBuilder
import SimpleITK as sitk
import numpy as np

pathd_ct = r'G:\03_projects\tmp\CT'
path_rs = r"G:\03_projects\tmp\RS.dcm"

# 
series_IDs = sitk.ImageSeriesReader.GetGDCMSeriesIDs(pathd_ct)
series_file_names = sitk.ImageSeriesReader.GetGDCMSeriesFileNames(pathd_ct, series_IDs[0])
series_reader = sitk.ImageSeriesReader()
series_reader.SetFileNames(series_file_names)
sio_CT= series_reader.Execute()
sitk.WriteImage(sio_CT, 'CT.nrrd')

# 
rtstruct = RTStructBuilder.create_from(
    dicom_series_path=pathd_ct,
    rt_struct_path=path_rs
)

npo_mask = rtstruct.get_roi_mask_by_name("PTVnx")  
# npo_mask = np.flip(npo_mask , axis=2) 
sio_mask = sitk.GetImageFromArray(npo_mask.astype(np.uint8).transpose(2, 0, 1)) 
sio_mask.CopyInformation(sio_CT) 
sitk.WriteImage(sio_mask, 'PTV.nrrd')
'''
