### ISSUE TITLE
ImplementationClassUID invalid

### ISSUE THREAD

**Issue by leokolezhuk** [qurit/rt-utils#14]
The **ImplementationClassUID (0002, 0012)** tag is set to an invalid value.

In [this line]( https://github.com/qurit/rt-utils/blob/20a27c48530a6c459cdeb7a869865ce7c770c677/rt_utils/utils.py#L31) it is set to _PYDICOM_ROOT_UID_ value defined in pydicom. 
This value is just the root of the pydicom's implementation UID and not the full UID("1.2.826.0.1.3680043.8.498."). The full implementation class UID of pydicom is defined in _PYDICOM_IMPLEMENTATION_UID_ ( "1.2.826.0.1.3680043.8.498.1")

Found out that it is invalid while running the DICOM validation tool [dciovfy](http://dclunie.com/dicom3tools/dciodvfy.html).

**Comment by awtkns** [comment]
HI @leokolezhuk thanks for bringing this to our attention. We have been also considering creating a custom implementation UID for RT-Utils

**Comment by leokolezhuk** [comment]
Thanks a lot for a fast response.
Nice library you are making!
