### ISSUE TITLE
get_contour_fill_mask: truncating contour data

### ISSUE THREAD

**Issue by clarkbab** [qurit/rt-utils#22]
Hi there,

It seems perhaps that you're rounding the contour data too early in your code. The contour_data is changed to type 'int' [here](https://github.com/qurit/rt-utils/blob/2378b3a2440420e2e2ea1889ad7a261dba9cc1c6/rt_utils/image_helper.py#L179), before being converted to the pixel coordinates. I think you can just remove `.astype(int)` as it's converted to 'int32' further on.

This change can make a difference to the resulting mask, please see attached example where I forked the code and applied the change to the fork:

https://colab.research.google.com/drive/1anBcwIGgrGcPDbsyIDrNqgb0H9UZxJhC?usp=sharing

**Comment by asim-shrestha** [comment]
I forget why exactly we performed the conversion at that stage. Most likely we can just remove it but I'll bring this up with the rest of the team.

Would you mind attaching you result images directly in this issue just so that they are easier to reference?

**Comment by clarkbab** [comment]
Sure, here's a 'Parotid-Left' slice with the current codebase first, and the forked codebase second:

![main](https://user-images.githubusercontent.com/18463586/118570568-c82d9880-b7bf-11eb-918e-c73555f4a003.png)
![fork](https://user-images.githubusercontent.com/18463586/118570576-cb288900-b7bf-11eb-880e-93b95199e629.png)

**Comment by clarkbab** [comment]
The other thing I would add, is that it might be an idea to round `contour_coords` before typecasting to avoid simply truncating floating point values.

**Comment by asim-shrestha** [comment]
@clarkbab I've testing the rounding change and it actually lead to some less accurate results within our basic mask accuracy tests like [this one](https://github.com/qurit/rt-utils/blob/2378b3a2440420e2e2ea1889ad7a261dba9cc1c6/rt_utils/image_helper.py#L179). In these tests we just compare the IOU over a new mask with that of the same mask just loaded from the RTStruct. What do you think?

**Comment by clarkbab** [comment]
@asim-shrestha is that the right link? Just took me to the original code we were discussing.

**Comment by clarkbab** [comment]
Not sure about your tests, but it seems the ITK library rounds the voxel index according to their [docs](https://itk.org/Doxygen/html/classitk_1_1ImageBase.html#a5c4f893aff7e68ffdc6ec4d6f592bb18).
