### ISSUE TITLE
Please remove "Skipping empty mask layer" print statement...

### ISSUE THREAD

**Issue by mathiser** [qurit/rt-utils#55]
... or at least make it with logging, so it can be filtered out.

Thanks for a wonderful library! 

Mathis

**Comment by asim-shrestha** [comment]
Hey Mathiser, thank you! You're right, we should definitely use a logger instead of just printing values out. Ill write a issue for that

Here is the PR to remove the print statement though: https://github.com/qurit/rt-utils/pull/57
