### ISSUE TITLE
Allow adding empty ROIs

### ISSUE THREAD

**Issue by mathiser** [qurit/rt-utils#56]
Dear rt-utils devs,
Does the dicom format allow adding empty ROIs? This would be extremely useful to be able to:
When a template rtstruct is made, our deep learning segmentation model does not always predict something for all labels. Thus, we just need to remember to add them manually later. With the possibility to add empty ROIs this problem is solved and making rt-utils even more useful.

Mathis

**Comment by asim-shrestha** [comment]
Hey again @mathiser, thanks for reaching out. What exactly do you mean by empty ROI's? Would you be able to use the existing add_roi function with just a completely empty 3D mask?

**Comment by mathiser** [comment]
@asim-shrestha,
Heading over here now :)
Yes, that was the idea - if it is possible. I don't know much about the DICOM format and if this is even supported. But by being able to generate empty structures, you can use rt-utils to generate template structures, which is highly valuable.

Mathis

**Comment by asim-shrestha** [comment]
@mathiser Updated and packaged https://pypi.org/project/rt-utils/1.2.5/!

**Comment by mathiser** [comment]
That's awesome, @asim-shrestha!
