### ISSUE TITLE
Contour Sequence should be optional.

### ISSUE THREAD

**Issue by MaxenceLarose** [qurit/rt-utils#67]
Hi,

Thank you for this awesome tool! 

*[Contour Sequence](https://dicom.innolitics.com/ciods/rt-dose/roi-contour/30060039/30060040)* is Type 3 (Optional), there's no guarantee it'll be present in a given item in the *ROI Contour Sequence*. I recently stumbled on `AttributeError: 'Dataset' object has no attribute 'ContourSequence'` while loading an existing RT Struct contour as a mask. 

I think this error should not occur. I managed to fix it and will make a pull request to review my correction.

Best,

Maxence

**Comment by asim-shrestha** [comment]
Hey Maxence, thanks for looking into this! Merged :)

**Comment by MaxenceLarose** [comment]
> Hey Maxence, thanks for looking into this! Merged :)

The pull request appears to have been closed instead of merged. Is it a mistake?
