### ISSUE TITLE
File type for ML masks

### ISSUE THREAD

**Issue by MattAWard** [qurit/rt-utils#83]
What file type/ format are the masks expected to be in to create the RTStruct files? We're currently trialling a ML auto segmentation solution which outputs anatomical models as separate nii.gz (zipped nifti) files. Do you know if files of this type can be converted into the required format for them to be packaged into an RTStruct file? Thanks.

**Comment by sunyu0410** [comment]
@MattAWard As long as you can convert the NIfTI file into a numpy array, then you can incorporate that using `rt-utils`. You can use `nibabel` to read a `nii.gz` and get the numpy array.
```python
import nibabel as nib

nii = nib.load('path/to/.nii.gz')
arr = nii.get_fdata()
```

**Comment by danihinjos** [comment]
Hi! How do you exactly convert a NifTI file in numpy array into a RTStruct? It's unclear :/
