### ISSUE TITLE
nifti mask to RT-struct dicom

### ISSUE THREAD

**Issue by qurit-frizi** [qurit/rt-utils#84]
I’ve recently designed a model which gives an output mask in nifti format. As I need to have rtstruct created as well, I am leveraging your rt_utils library.
Below is the code I wrote for the same. I am getting the rtstruct which seems to be rotated of flipped. The snapshot shows both nifti mask and generated Dicom rtstruct. Just wanted to check if you’ve happened to see such behavior? It would be great if you could share your thought/recommendations to address this issue.

![image](https://user-images.githubusercontent.com/84542058/221669230-9851d0a1-93e6-4aa8-9b90-35be7c445b4c.png)

![image](https://user-images.githubusercontent.com/84542058/221668348-5a2edb04-a22a-45d0-9ba2-9086409e4d46.png)

**Comment by qurit-frizi** [comment]
I will add a function to solve this issue.

**Comment by MattAWard** [comment]
Hi Qurit could I ask what your solution was for this? I'm having the same problem...
![rotated_screengrab](https://user-images.githubusercontent.com/119061663/225906937-d4a7b1c5-95fc-432d-aa7b-3f15e1aaeea2.png)

**Comment by pritamrungta** [comment]
Hi @qurit-frizi 
I'm in a similar situation.
Any ideas to fix would be really helpful.

**Comment by pritamrungta** [comment]
Hi @MattAWard 
Thanks for the info.
I had thought of something in the similar lines,
but turns out it isn't a generalized solution (atleast didn't work for my images 😔)

**Comment by pritamrungta** [comment]
I had to eventually do `arr.swapaxes(0, 1)` instead of rotation on the data returned by nibabel.
Still open for feedback.
