### ISSUE TITLE
Preferred Way to Cite this Repository

### ISSUE THREAD

**Issue by edwardwang1** [qurit/rt-utils#89]
I have used rt-utils in some of my research that I am writing up (it has been super useful!). What is the preferred way to cite this repository?

Thanks,
Edward

**Comment by carluri** [comment]
@edwardwang1 we are working on writing the manuscript of this with @asim-shrestha, @awtkns and @qurit-frizi. 

For now please refer to the RT-Utils repository like this:

Shrestha Asim, Watkins Adam, Uribe Carlos. RT-Utils: A minimal Python library for RT Struct manipulation. (2020). https://github.com/qurit/rt-utils

Please reach out before you submit your research to see if I can give you an update about the paper to cite.

Thank you and hope this tool keeps helping you moving forward.
